# Generated by Django 3.0.5 on 2020-05-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('werewolf', '0005_add_new_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elect_date', models.CharField(default='0 18 * * *', max_length=32)),
                ('murder_date', models.CharField(default='0 22 * * *', max_length=32)),
                ('wich_date', models.CharField(default='0 2 * * *', max_length=32)),
                ('resolution', models.CharField(default='0 6 * * *', max_length=32)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Game')),
            ],
        ),
        migrations.CreateModel(
            name='NextStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('VOTE', 'Vote'), ('MURDER', 'Murder'), ('WITCH', 'Witch'), ('RESOL', 'Resolution')], default='VOTE', max_length=6)),
                ('when', models.DateTimeField()),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Game')),
            ],
        ),
    ]
