# Generated by Django 3.0.5 on 2020-04-16 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('werewolf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NONE', 'Undefined'), ('HUMA', 'Human'), ('WOLF', 'Werewolf')], default='NONE', max_length=4)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'owner')},
            },
        ),
    ]
