# Generated by Django 4.0 on 2022-01-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_create_user'),
        ('werewolf', '0002_create_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NONE', 'Undefined'), ('HUMA', 'Human'), ('WOLF', 'Werewolf'), ('SEER', 'Seer'), ('CUPD', 'Cupidon'), ('WTCH', 'Witch')], default='NONE', max_length=4)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.game')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'unique_together': {('game', 'owner')},
            },
        ),
    ]
