# Generated by Django 3.0.5 on 2020-04-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0003_add_round'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': (('can_elect', 'Elect a player to be mayor'), ('can_vote', 'Vote against a player to be hanged'), ('can_murder', 'Werewolf vote to kill someone'), ('can_predict', 'Seer hability to predict someone character'), ('can_link', 'Cupidon hability to link to player to death'), ('can_save', 'Witch hability to save someone'), ('can_poison', 'Witch hability to kill someone'))},
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Round')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Round')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Round')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Round')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Murder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Round')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Round')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Round')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
