# Generated by Django 3.0.5 on 2020-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0004_add_actions_and_game_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='type',
            field=models.CharField(choices=[('NONE', 'Undefined'), ('HUMA', 'Human'), ('WOLF', 'Werewolf'), ('SEER', 'Seer'), ('CUPD', 'Cupidon'), ('WTCH', 'Witch')], default='NONE', max_length=4),
        ),
    ]
