
name: Code Quality CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  tests:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10.4"
    - name: Run poetry image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.11
    - name: Instal dependencies
      run: |
          poetry install
    - name: Run Tests
      run: |
        cd werewolf/
        poetry run pytest


  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
      - uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8
